---
title: 'CrisisEvents.org - High Quality International Relations Event Data'
output:
  html_document:
    toc: no
    self_contained: no
    lib_dir: 'lib'
---

<style>
    body .main-container {
        max-width: 1500px;
    }
</style>


```{js, class.source = "jsvis1", echo=F}
window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
    t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);

  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };

  return t;
}(document, "script", "twitter-wjs"));
```


Over 10,000 human coded events from 470 pivotal crises in international relations in the new ICBe dataset (International Crises Behavior events). Use this website to visualize the data and compare to pre-existing state of the art event datasets. Read our [introduction to the data paper](https://github.com/CenterForPeaceAndSecurityStudies/ICBEdataset/raw/master/paper/ICBEdataset_paper_rex.pdf) and [download the data for free](https://github.com/CenterForPeaceAndSecurityStudies/ICBEdataset) for your own work. <a class="twitter-share-button" href="https://twitter.com/intent/tweet?text=Hello%20world">Tweet</a>

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@site_username">
<meta name="twitter:title" content="Top 10 Things Ever">
<meta name="twitter:description" content="Up than 200 characters.">
<meta name="twitter:creator" content="@creator_username">
<meta name="twitter:image" content="http://placekitten.com/250/250">
<meta name="twitter:domain" content="YourDomain.com">

```{r setup, include=FALSE, echo=F, results='hide',  include=T, message=F, cache=F, warning=F}

#PhantomJS not found. You can install it with webshot::install_phantomjs(). If it is installed, please make sure the phantomjs executable can be found via the PATH variable.
#webshot::install_phantomjs()

source('/mnt/8tb_a/rwd_github_private/icbe/docs/maps.r')


#On how to reset the repo to save space
#https://github.com/18F/C2/issues/439

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

icb_crises <-readRDS(paste0(here::here(), "/docs/icb1v14.Rds") )

icb_crises$decade <- floor(icb_crises$yrtrig/10)*10
icb_crises$decade_5 <- icb_crises$decade  + (icb_crises$yrtrig %% 10 > 5)*5

fromscratch=F
library(glue)
n <- 476
chunk <- function(x,n) split(x, factor(sort(rank(x)%%n)))
chunks <- chunk(1:n,30)

df <- sapply(chunks, range) %>% t() %>% as.data.frame() %>%
  mutate(filenames_html = glue("ICBe_Website_Cases_{V1}to{V2}.html")) %>%
  mutate(filenames_rmd = glue("/mnt/8tb_a/rwd_github_private/icbe/docs/ICBe_Website_Cases_{V1}to{V2}.rmd")) %>%
  mutate(link = glue("[{V1}-{V2}](ICBe_Website_Cases_{V1}to{V2}.html);"))


```



```{r, echo=F, results='asis',  include=T, message=F, cache=F, warning=F}

cat('\n\n# {.tabset .tabset-fade .tabset-pills}\n\n') #Start tabs for decades

for(d in na.omit(unique(icb_crises$decade))){ #for debuging can limit it to just 2 decades #[1:2]
  
  #Start tab for cases
  if( d==1960){ cat('\n\n## ', d , ' {.active .tabset .tabset-fade .tabset-pills} \n\n') } else {
    cat('\n\n## ', d , ' {.tabset .tabset-fade .tabset-pills} \n\n' )  
  }

  for(year in icb_crises %>% filter(decade %in% d) %>% pull(yrtrig) %>% unique() ) {
    if( year==1962){ cat('\n\n### ', year , ' {.active .tabset .tabset-fade .tabset-pills} \n\n') } else {
      cat('\n\n### ', year , ' {.tabset .tabset-fade .tabset-pills} \n\n' )  
    }  
    
    for(crisis in icb_crises %>% filter(yrtrig %in% year) %>% pull(crisno) ) { 
      map(crisis, fromscratch=F)
    }
  #cat('\n\n## {-}\n\n') #Close tab for cases
  }
}
cat('\n\n# {-}\n\n') #Close tab for decades

```
